# Generated by Django 3.2.4 on 2021-06-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='imdbID',
            new_name='imdbId',
        ),
    ]
