# Generated by Django 3.2.4 on 2021-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0002_rename_imdbid_video_imdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Year'),
        ),
    ]
