# Generated by Django 3.2.4 on 2021-06-28 11:05

from django.db import migrations, models
import omdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0003_alter_video_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.CharField(db_index=True, max_length=9, validators=[omdb.models.year_range_validator], verbose_name='Year'),
        ),
    ]
