# Generated by Django 3.2.4 on 2021-06-30 08:46

from django.db import migrations, models
import omdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0004_alter_video_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='imdbId',
            new_name='imdb_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'Series'), ('EPISODE', 'Episode')], db_index=True, max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='year',
            field=models.CharField(max_length=9, validators=[omdb.models.year_range_validator], verbose_name='Year'),
        ),
    ]
